[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font]
size = 18

[font.bold]
family = "Iosevka NFP"
style = "Bold"

[font.bold_italic]
family = "Iosevka NFP"
style = "Bold Italic"

[font.italic]
family = "Iosevka NFP"
style = "Italic"

[font.normal]
family = "Iosevka NFP"
style = "Regular"

[window]
opacity = 1.0
# <<<<<<< HEAD
# # option_as_alt = "OnlyLeft"
# =======
# option_as_alt = "OnlyLeft"
# >>>>>>> 197e2a9 (tmux nvim)
startup_mode = "Maximized"
title = "Terminal"

[window.padding]
x = 5
y = 5
