[font]
normal = { family = "Iosevka NF", style = "Medium" }
#bold = { family = "<string>", style = "<string>" }
#italic = { family = "<string>", style = "<string>" }
#bold_italic = { family = "<string>", style = "<string>" }
size = 12
#offset = { x = 0, y = 0 }
# glyph_offset = { x = <integer>, y = <integer> }
# builtin_box_drawing = true | false

[terminal.shell]
program = "wsl ~"